### PR TITLE
feat: add nodeSelector, pod tolerations, node affinity configuration

### PR DESCRIPTION
**Pull request by dmakeroam**
It would be good to filter pod schedule on some nodes, so I added this feature.

### CODE REVIEW

**Comment by dmakeroam** [comment]
@eshepelyuk Please help to review it

**Comment by eshepelyuk** [comment]
Thanks for your contribution. I ll review the PR with more details this week.
But currently I have following requests

1. Valeues must be reflected in JSON schema
1. It is require to add linting tests fro new values, as soon as schema changed
1. Plz use `nindent` in templates

**Comment by dmakeroam** [comment]
@eshepelyuk Any updates on this?

**Comment by ievgenii-shepeliuk** [comment]
Sorry, I didnt have time to review this. Hope will be doing a review this week.

**Comment by eshepelyuk** [comment]
Hello @dmakeroam 

I am going to introduce breaking changes into a project, so I would like to understand the state of this PR, before I do it.
My intention is to wait as much as possible until you complete this contribution, so I can roll out a new release without breaking changes. 
And then, make my breaking changes.

Please, describe your plans and intentions, so I can schedule my work on the project.
Thanx !

**Comment by dmakeroam** [comment]
nodeSelector,  pod tolerations, node affinity configuration might be good features for the project, but right now I haven't much time to figure out. 

To not block your changes, I would try to finish it by tomorrow.

**Comment by eshepelyuk** [comment]
Look @dmakeroam I can pick up this PR and finish myself.

Let's do it like this ?

**Comment by dmakeroam** [comment]
> 

You can sir, if you can't wait more

**Comment by eshepelyuk** [comment]
> > 
> 
> You can sir, if you can't wait more

Well, the PR is almost done, so only cosmetic changes are left. Dont worry I will complete PR by myself.

**Pull request merged**
