### PR TITLE
Allow the user to pass podAnnotations to the underlying job

### PR DESCRIPTION
**Pull request by jack1902**
This enables the cmak-reconcile jobs spun up to have additional podAnnotations passed. This is especially useful in a namespace which is being automatically injected by a service-mesh but is undesirable on jobs which are finite (linkerds sidecar will run forever resulting in the cmak-reconcile pod never dying if injected).

### CODE REVIEW

**Comment by eshepelyuk** [comment]
Hello @jack1902 
thanks for a contribution.

**Review by eshepelyuk — CHANGES_REQUESTED** [review]
1. Read carefully [CONTRIBUTING](https://github.com/eshepelyuk/cmak-operator/blob/master/CONTRIBUTING.adoc) and adjust your commits accordingly
1. Rename `podAnnotations` to `annotations`
1. Tests - this project has lint tests / unit tests and e2e tests. For this case you should add linter tests and unit tests. Check `test` fodler.

**Comment by jack1902** [comment]
@eshepelyuk unsure of how to run the tests locally for this project, but I have updated from `podAnnotations` to `annotations` as requested.

The `annotations` are additive but won't break backwards compatibility so in theory the tests that exist now should still function unless they are string comparisons?

**Comment by eshepelyuk** [comment]
@jack1902 - 

1. check CI / CD pipeline how to run linter and unit tests locally https://github.com/eshepelyuk/cmak-operator/blob/master/.github/workflows/ci.yaml#L21-L24
1. When running linter tests locally - ignore the output, just analyze final return code - must be 0

**Comment by jack1902** [comment]
@eshepelyuk added some tests around the annotation addition and the stuff is passing
image

**Comment by jack1902** [comment]
@eshepelyuk I've added additional annotations for the `job-setup` created via a helm hook as this caught me off guard when deploying this locally to my environment. I've added additional tests to cover this as it was easy enough once I understood how the helm unittest plugin worked

**Review by eshepelyuk — CHANGES_REQUESTED** [review]
1. In general setup job is a workaround for reconcile job. Id suggest to apply `reconcile.annotations` to both jobs, just to not overcomplicate helm values.
1. Dont put tests into existing placement suite, create a new one for both setup and reconcile manifests.
1. Also add a test for default case, i.e. annotations is empty, and check that rendered manifests dont have any annotations

**Comment by jack1902** [comment]
@eshepelyuk i've used the single `annotations` now for both jobs and added tests for this work which cover your point `3` since annotations are only added if they exist otherwise `metadata` doesn't exist (which is desirable for the chart as it wasn't present previously)

**Review by eshepelyuk — CHANGES_REQUESTED** [review]
Well, point by point

1. rollback file `test/unit/reconcile-placement.yaml`
1. merge `test/unit/reconcile-annotations.yaml` and `test/unit/setup-annotations.yaml` into a new file `test/unit/job-annotations.yaml`
1. in `test/unit/setup-annotations.yaml` both for cron job and for job manifests add test cases when you don't pass any annotaitons to values, i.e. case by default

**Review by eshepelyuk — CHANGES_REQUESTED** [review]
plz keep only changes related to jobs. plz remove pod / deployment changes>
the PR is getting overcomplicated.

**Comment by eshepelyuk** [comment]
> Well, point by point
> 
> 1. rollback file `test/unit/reconcile-placement.yaml`
> 2. merge `test/unit/reconcile-annotations.yaml` and `test/unit/setup-annotations.yaml` into a new file `test/unit/job-annotations.yaml`
> 3. in `test/unit/job-annotations.yaml` both for cron job and for job manifests add test cases when you don't pass any annotaitons to values, i.e. case by default

@jack1902 plz follow this exactly as written

**Comment by jack1902** [comment]
merged the files and added a new set of annotations to the deployment which are also covered by tests.

**Comment by jack1902** [comment]
@eshepelyuk ive got the changes in this for the deployment, if you are happy with all the changes here, i can open a second PR to merge the deployment changes too.

**Comment by eshepelyuk** [comment]
@jack1902 please read all comments cafefully and apply all of the requested changes, exactly as written.

**Comment by jack1902** [comment]
1. rollback file test/unit/reconcile-placement.yaml - no longer shows up in the diff
2. merge test/unit/reconcile-annotations.yaml and test/unit/setup-annotations.yaml into a new file test/unit/job-annotations.yaml - completed
3. in test/unit/job-annotations.yaml both for cron job and for job manifests add test cases when you don't pass any annotaitons to values, i.e. case by default - this is exactly what is covered by the `should not have annotations by default` test, please elaborate what is missing with a useful contribution or example as I am confused as to what you mean if this is not the case.


I have dropped the deployment annotations entirely.

**Review by eshepelyuk — CHANGES_REQUESTED** [review]
Plz remove test/unit/setup-annotations.yaml, it is a duplication.

**Comment by jack1902** [comment]
Completed, i can't merge the two commits on my mobile so I'll have to do this tomorrow if this is a blocker for the  pr merging

**Review by eshepelyuk — CHANGES_REQUESTED** [review]
Plz rebase and squash into single commit, according to CONTRIBUTING page.
LGTM otherwise, ready to merge.

**Comment by eshepelyuk** [comment]
> Completed, i can't merge the two commits on my mobile so I'll have to do this tomorrow if this is a blocker for the pr merging

Ahh ok z i ll do it

**Comment by eshepelyuk** [comment]
@jack1902 thnx for contrivution.
I ll merge this PR and i am ready to new one regarding the deployemnt annotations.

Then i ll create a new release.
Makes sense ?

**Comment by jack1902** [comment]
Makes sense, thanks for the merge. The annotations for the deployment don't matter as much, since the annotations I needed actually had to go on zookeeper to enable my deployment of Kafka to work.

The annotations to disable service mesh injection on the jobs was the main blocker I originally ran into

**Comment by eshepelyuk** [comment]
Well, then I am making a release now.

**Pull request merged**
